function correctCase(unformattedPlaceArr) {
  const formattedPlaceArr = []
  unformattedPlaceArr.forEach((place) => formattedPlaceArr.push(place.toLowerCase().replace(/\b\w/g, l => l.toUpperCase())))
  return formattedPlaceArr;
}

const hotelesCancun = [
  "Aloft Cancun	Blvd. Kukulcan Km 9, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Altitude by Krystal Grand Punta Cancun-All Inclusive	Blvd Kukulcan km 8.5, Cancun Zona Hotelera Punta Cancun",
  "Ambiance Suites Cancun	Av. Tulum Mz. 9, Lot. 41 y 42, #227, SM. 20, Cancun Centro (Ciudad)",
  "Amigo Rental	Blvd. Kukulcan km 19.5, Cancun Zona Hotelera Mar Caribe",
  "Aquamarina Beach	Boulevard Kukulkan km 4.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Beach Palace	Blvd Kukulcan KM 11.5, Cancun Zona Hotelera Mar Caribe",
  "Beachscape Kin Ha Villas and Suites	Bvld. Kukulcan Km. 8.5 Zona Hotelera, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Bel Air Collection Resort and Spa Cancun All Inclusive	Blvd. Kukulkan Km. 20.5, Cancun Zona Hotelera Mar Caribe",
  "Blue Coconut Cancun	Sm 65 Calle 16 Lt 15 y 16 Mz 2, Cancun Centro (Ciudad)",
  "Bsea Cancun Plaza	Blvd. Kukulcan Km. 20.5, Cancun Zona Hotelera Mar Caribe",
  "Calypso Hotel	Blvd. Kukulcan Km. 4 Lote D-8, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Cancun Bay Resort All Inclusive	Paseo Kukulcan Km. 3.5 Zona hotelera, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Cancun Clipper Club	Blvd. Kukulcan, Km. 8.5, Cancun Zona Hotelera Punta Cancun",
  "Cancun International Suites	Gladiolas Mza. 16 Lt. 11, Cancun Centro (Ciudad)",
  "Caribe Internacional	AV. YAXCHILAN Y SUNYAXCHEN No. 36, Cancun Centro (Ciudad)",
  "Casa Maya Cancun	Boulevard Kukulcan Km. 5.5 Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Casa Turquesa Hotel Boutique and Museum	Blvd. Kukulcan km 13.5, Cancun Zona Hotelera Mar Caribe",
  "City Express Cancun	Calle Nichupte s/n S.M.8, Mza. 1, Lote 4, Cancun Centro (Ciudad)",
  "City Express Junior Cancun	Av. Nichupte SM 8 Manzana 1 Lote 3, Cancun Centro (Ciudad)",
  "Club Med Cancun	Boulevard Kukulcan Km. 20, Cancun Zona Hotelera Mar Caribe",
  "Comfort Inn Cancun Aeropuerto	Carr. Cancun - Aeropuerto M4L5 SM301, Cancun Zona Aeropuerto",
  "Condominios Salvia	Blvd. Kukulcan Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Courtyard by Marriott Cancun Airport	Bvl. Luis Donaldo Colosio Km. 12.5 Lte. 1 SMZA.301, Cancun Zona Aeropuerto",
  "Crown Paradise Club Cancun	Blvd. Kukulcan 18.5, Cancun Zona Hotelera Mar Caribe",
  "Dreams Sands Cancun Resort and Spa	Blvd. Kukulkan km 8.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Emporio Cancun	Blvd. Kukulcan, Retorno Gucumatz, Km. 17 Lt 49, Cancun Zona Hotelera Mar Caribe",
  "Fiesta Americana Cancun Villas	Blvd Kukulcan KM 8.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Fiesta Americana Condesa Cancun All Inclusive	Blvd. Kukulcan Km. 16.5 Lote 3, Cancun Zona Hotelera Mar Caribe",
  "Fiesta Inn Cancun Las Americas	Av. Bonampak Lote 1, Manzana 1, Cancun Centro (Ciudad)",
  "Flamingo Cancun Resort	Blvd. Kukulcan Km 11, Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Four Points By Sheraton Cancun Centro	Av. Tulum Mz 1 Lt. 2, Cancun Centro (Ciudad)",
  "Golden Parnassus Resort and Spa	Blvd. Kukulcan Km. 14.5 Retorno Sn. Miguelito · 37, Cancun Zona Hotelera Mar Caribe",
  "GR Caribe by Solaris Deluxe All Inclusive Resort	Blvd. Kukulkan Km. Lote 64 2a etapa, seccion A, Cancun Zona Hotelera Mar Caribe",
  "GR Solaris Cancun	Blvd. Kukulcan Km. 19.5 Lote 59-2, Cancun Zona Hotelera Mar Caribe",
  "Grand City Hotel	Av Yaxchilan 154, Cancun Centro (Ciudad)",
  "Grand Fiesta Americana Coral Beach Cancun	Blvd. Kukulcan Km. 9.5 Lote 6, Zona Hotelera, Cancun Zona Hotelera Punta Cancun",
  "Grand Oasis Cancun	Blvd. Kukulcan Km. 16.5, Cancun Zona Hotelera Mar Caribe",
  "Grand Oasis Palm	Boulevard Kukulcan km 4.5, Cancun Zona Hotelera Mar Caribe",
  "Grand Oasis Sens	Blvd. Kukulcan Km. 19.5, Cancun Zona Hotelera Mar Caribe",
  "Grand Park Royal Cancun	Blvd. Kukulcan Km. 10.5, Cancun Zona Hotelera Mar Caribe",
  "Grand Royal Lagoon	Blvd. Kukulcan K.m. 7.5 Zona Hotelera, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Hampton Inn by Hilton Cancun Cumbres	SM 310 MZ 01 L-4-02 Blvd. Luis Donaldo Colosio, Cancun Zona Aeropuerto",
  "Hard Rock Hotel Cancun	Kukulcan Blvd. Km 14.5, Cancun Zona Hotelera Mar Caribe",
  "Hideaway at Royalton Riviera Cancun Solo Adultos	Carretera Federal 307 Tulum-Cancun Km 322, 15, Puerto Morelos",
  "Holiday Inn Cancun Arenas	Boulevard Kukulcan 2,5 km, Lt. D1, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Hostal ikaro Beds	Sunyaxchen 16 Mz 5 Lote 58, Cancun Centro (Ciudad)",
  "Hotel Adhara Hacienda Cancun	Avenida Nader 1,2,3 SM. 2, Cancun Centro (Ciudad)",
  "Hotel and Spa Xbalamque Cancun Centro	Av. Yaxchilan No. 31 Mz.18 Lt. 18 SM 22, Cancun Centro (Ciudad)",
  "Hotel Antillano	Avenida Tulum y Calle Claveles No. 1 SM-22, Cancun Centro (Ciudad)",
  "Hotel Batab	Av.Chichen Itza #52 Sm 23, Cancun Centro (Ciudad)",
  "Hotel Colonial Cancun	Tulipanes 22 Mza 2 SM 22 por Avenida Tulum, Cancun Centro (Ciudad)",
  "Hotel Green 16	Av. Pok Ta Pok Lotes 4, 5 y 6, Cancun Zona Hotelera Laguna",
  "Hotel Hacienda Cancun	Av. Sunyaxchen Mz 22 Lt 39 y 40 Av. Xel-Ha SM 24, Cancun Centro (Ciudad)",
  "Hotel Hacienda de Castilla	Calle 17 Sm. 64 Mza. 23 Lotes 9 al 14, Cancun Centro (Ciudad)",
  "Hotel HC Internacional	Av. Uxmal 44 Sm 22 Mza 24, Cancun Centro (Ciudad)",
  "Hotel ikaro Suites Cancun	Sunyaxchen #16 Sm 25 Mz 25 Lote 58, Cancun Centro (Ciudad)",
  "Hotel Imperial Laguna Faranda Cancun	Calle Quetzal No 11, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Hotel Margaritas Cancun	Avenida Nader 1,2,3 SM. 2, Cancun Centro (Ciudad)",
  "Hotel Maya Caribe Faranda Cancun	Paseo Kukulcan Km. 6, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Hotel NYX Cancun	Blvd Kukulkan Km. 11.5 ZH, Cancun Zona Hotelera Mar Caribe",
  "Hotel Parador	Av. Tulum Manzana 12 Lote 26 SM 5, Cancun Centro (Ciudad)",
  "Hotel Plaza Kokai Cancun	Av.Uxmal No.26 SM. 2-A MZA. 3 Lotes 15 y 16, Cancun Centro (Ciudad)",
  "Hotel Suites Cancun Center	Alcatraces Num32 SM 22 Manzana 10, Cancun Centro (Ciudad)",
  "Hyatt Zilara Cancun	Av. Kukulcan Km. 11.5, Cancun Zona Hotelera Mar Caribe",
  "Hyatt Ziva Cancun	Blvd. Kukulcan Mza. 51 Punta Cancun Lote 7, Cancun Zona Hotelera Mar Caribe",
  "Iberostar Selection Cancun	Boulevard Km. 17, Cancun Zona Hotelera Mar Caribe",
  "Ibis Cancun Centro	M2 L3, Av. Tulum y Nichupte, Cancun Centro (Ciudad)",
  "Imperial Las Perlas	Blvd. Kukulcan Km. 2.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "JW Marriott Cancun Resort and Spa	Blvd Kukulkan Km 14.5 2da. Etapa Lote 40-A, Cancun Zona Hotelera Mar Caribe",
  "Krystal Cancun	Blvd, Kukulcan Km 9, Cancun Zona Hotelera Punta Cancun",
  "Krystal Cancun All Inclusive	Blvd, Kukulcan Km 9, Cancun Zona Hotelera Punta Cancun",
  "Krystal Grand Punta Cancun	Boulevard Kukulcan Km. 8.5, Zona Hotelera, Cancun Zona Hotelera Punta Cancun",
  "Krystal Urban Cancun Centro	Av Sayil SM 4 Mza 1 Lote 4-7 a lado Plaza de Toros, Cancun Centro (Ciudad)",
  "La Quinta by Wyndham Cancun	Avenida Tulum, S. M. 4, Mza. 14, Lote 2, Cancun Centro (Ciudad)",
  "Laguna Suites Golf & Spa	Pok-Ta-Pok 3, Cancun Zona Hotelera Mar Caribe",
  "Las Gaviotas Hotel and Suites	Paseo Poktapok Lote 1 Zona Turistica, Cancun Zona Hotelera Mar Caribe",
  "Le Blanc Spa Resort	Blvd. Kukulcan Km. 10, Cancun Zona Hotelera Mar Caribe",
  "Live Aqua Beach Resort Cancun	Blvd. Kukulcan K.m 12.5 Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Marazul Hotel Boutique	Av. Nader, Mojarra No 17 Sm 3 Mza 6, Cancun Centro (Ciudad)",
  "Marriott Cancun Resort	Blvd. Kukulcan, retorno chac L-41 Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Melody Maker Cancun	Boulevard Kukulkan km 12, Cancun Zona Hotelera Mar Caribe",
  "Mia Cancun Resort	Kukulcan blvd. Km 11.5 ZH, Cancun Zona Hotelera Mar Caribe",
  "Moon Palace Cancun	Carretera Cancun-Chetumal Km. 36.5, Puerto Morelos",
  "Nizuc Resort and Spa	Boulevard Kukulkan km 21+260 lote 1-01 Manzana 59, Cancun Zona Hotelera Mar Caribe",
  "Oasis Cancun Lite	Blvd. Kukulcan km 16.5, Cancun Zona Hotelera Mar Caribe",
  "Oasis Palm	Boulevard Kukulcan Secc. C Lote -1, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Occidental Costa Cancun	Blvd. Kukulkan km 4.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Occidental Tucancun	Blvd. Kukulkan Km. 13.5 Lote 24, Cancun Zona Hotelera Mar Caribe",
  "Ocean Dream Cancun	Blvd. Kukulcan Km 9.5, Cancun Zona Hotelera Mar Caribe",
  "Ocean Spa Hotel	Blvd. Kukulcan km 3.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Oh Cancun The Urban Oasis	Av. Brisa Mza 19 L 01 y 03 Sm 4 Av Tulum, Cancun Centro (Ciudad)",
  "Oleo Cancun Playa All Inclusive Boutique Resort	Blvd. Kukulcan Km. 19.5, Cancun Zona Hotelera Mar Caribe",
  "Omni Cancun Hotel and Villas	Boulevard Kukulkan L-48 Km. 16.5 M.53, Cancun Zona Hotelera Mar Caribe",
  "One Cancun Centro	Av. Tulum Esq, Banco Chinchorro Lote 1-01 Manzana, Cancun Centro (Ciudad)",
  "Panama Jack Resorts Gran Caribe Cancun	Blvd. Kukulcan km 11.5, Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Paradisus Cancun Resort by Melia	Blvd Kukulcan km. 16.5, Cancun Zona Hotelera Mar Caribe",
  "Park Royal Beach Cancun	Blvd. Kukulcan KM 12.5, Cancun Zona Hotelera Mar Caribe",
  "Pa'Xa Mama Hotel Boutique	Av Tulum con Claveles No.119 Sm.22 Mz.6 Lt 41-01, Cancun Centro (Ciudad)",
  "Plaza Caribe Cancun	Av. Tulum con Av. Uxmal, Cancun Centro (Ciudad)",
  "Presidente InterContinental Cancun Resort	Boulevard Kukulcan km 7.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Ramada by Wyndham Cancun City	Ave Yaxchilan 41 S.M. 22, Cancun Centro (Ciudad)",
  "Real Inn Cancun	Km 5.5 Boulevard Kukulkan, Cancun Zona Hotelera Mar Caribe",
  "Riu Cancun	BLVD. KUKULCAN KM 9 ZONA HOTELERA, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Riu Caribe	Blvd. Kukulcan Km. 5.5 Zona Hotelera, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Riu Palace Las Americas	Blvd. Kukulcan K.m 8.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Riu Palace Peninsula All Inclusive	Blvd Kukulcan Km 5.5 Lote 6-C Z.H., Cancun Z. Hotelera Bahia Isla Mujeres",
  "Royal Service by Paradisus Cancun	Blvd Kukulcan km. 16.5, Cancun Zona Hotelera Mar Caribe",
  "Royal Solaris Cancun	Blvd. Kukulcan Km. 20 Lote 64, Cancun Zona Hotelera Mar Caribe",
  "Royal Sunset Beach Resort	Blvd Kukulcan km 10 zona hotelera, Cancun Zona Hotelera Mar Caribe",
  "Royalton Riviera Cancun Resort and Spa	Carretera Federal 307 Tulum-Cancun Km 322, 15 Sm31, Puerto Morelos",
  "Sandos Cancun All Inclusive	Boulevard Kukulkan Km 14, Zona Hotelera Cancun, Cancun Zona Hotelera Mar Caribe",
  "Seadust Cancun Family Resort	Blvd. Kukulcan Km. 16.9 lote 52-04, Cancun Zona Hotelera Mar Caribe",
  "Secrets The Vine Cancun	Blvd Kukulkan Km 14.5, Retorno Ixchel, Lot 38, Cancun Zona Hotelera Mar Caribe",
  "Smart Cancun by Oasis	Av. Tulum Esq. Brisas s/n SM4 , M21, Cancun Centro (Ciudad)",
  "Soberanis Cancun	Av. Coba 5 y 7, Mza. 8, S.M. 22, Cancun Centro (Ciudad)",
  "Solymar Beach Resort	Blvd. Kukulcan Km. 18.7 Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "Sotavento	Zona Hotelera km. 3.5, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Suites Gaby Hotel	Av. Sunyaxchen Lote 46 y 47 Mza 2, Cancun Centro (Ciudad)",
  "Suites Malecon Cancun by Torre Vancouver	Av. Bonampak Sm 6 M1 L1, Cancun Centro (Ciudad)",
  "Sun Palace	Paseo Kukulkan Km. 10, Cancun Zona Hotelera Mar Caribe",
  "Sunset Marina Resort & Yacht Club	Boulevard Kukulkan Km 5.8, Cancun Z. Hotelera Bahia Isla Mujeres",
  "Temptation Cancun Resort	Km. 3.5 Blvd. Kukulcan, Cancun Zona Hotelera Laguna",
  "Terracaribe	Av. Lopez Portillo No. 70 Mza. 33, Cancun Centro (Ciudad)",
  "The Caribbean Princess	Galeon D9-5, Km. 3.5,, Cancun Z. Hotelera Bahia Isla Mujeres",
  "The Grand at Moon Palace	Carretera Cancun-Chetumal Km. 36.5, Cancun Zona Hotelera Mar Caribe",
  "The Pyramid at Grand Oasis	Blvd. Kukulcan 16.5, Cancun Zona Hotelera Mar Caribe",
  "The Ritz-Carlton Cancun	Retorno del Rey Lote 36, Zona Hotelera, Cancun Zona Hotelera Mar Caribe",
  "The Royal Cancun All Suites Resort	Kukulcan Boulevard km 4.5 Hotel Zone, Cancun Zona Hotelera Mar Caribe",
  "The Royal Caribbean An All Suites Resort	Kukulcan Blvd. Km 17, Cancun Zona Hotelera Mar Caribe",
  "The Royal Islander An All Suites Resort	Kukulcan Blvd. Km. 17.5, Cancun Zona Hotelera Mar Caribe",
  "The Royal Sands Resort and Spa All Inclusive	Kukulcan Blvd. Km 13.5, Cancun Zona Hotelera Mar Caribe",
  "The Westin Lagunamar Ocean Resort Villas Cancun	Blvd. Kukulkan Km. 12, Cancun Zona Hotelera Mar Caribe",
  "The Westin Resort and Spa Cancun	Blvd. Kukulcan 20 Km., Cancun Zona Hotelera Mar Caribe",
  "Turquoize at Hyatt Ziva Cancun - Adults Only - All Inclusive	Blvd. Kukulcan Manzana 51 Lote 7, Cancun Zona Hotelera Mar Caribe",
];

const hotelesPuertoJuarez = [
  "All Ritmo Cancun Resort and Waterpark	Km. 1.5 carretera a Puerto Juarez Punta Sam, Cancun Puerto Juarez",
  "Hotel del Sol	Av. Lopez Portillo Mza 2 L 1 a SM85, Cancun Puerto Juarez",
  "Ferry Puerto Juarez	Km. 2.5 carretera a Puerto Juarez Punta Sam, Cancun Puerto Juarez",
  "Muelle Ultramar	Km. 2 carretera a Puerto Juarez Punta Sam, Cancun Puerto Juarez",
];

const hotelesPlayaMujeres = [
  "Excellence Playa Mujeres	Condominio Playa Mujeres lote 1 mz.1 sm.3, Cancun Playa Mujeres",
  "Villa del Palmar Cancun Luxury Beach Resort and Spa	Carretera Punta Sam Km 5.2 Mz-9 Lote-3 SM-2, Cancun Playa Mujeres",
  "Finest Playa Mujeres	Vialidad Paseo Mujeres Mza.1 Lt.10 Sm.3, Cancun Playa Mujeres",
  "Riu Dunamar	Blvd. Costa Mujeres, Cancun Playa Mujeres",
  "Secrets Playa Mujeres Golf and Spa Resort Todo Incluido - Solo Adultos	Lote RTH-7-PM-II Lte1, MZA1, SM3, Cancun Playa Mujeres",
  "Dreams Playa Mujeres Golf and Spa Resort	Lote RTH-7-PM-II, Lte 1, Mza 1, Sm 3, Cancun Playa Mujeres",
  "The Beloved Hotel Playa Mujeres Boutique All Inclusive	Playa Mujeres, Cancun Playa Mujeres",
];

const hotelesPuertoMorelos = [
  "Arrecifes Suites	Heriberto Frias Sm.02 Mza.14 Lt.7, Puerto Morelos",
  "Azul Beach Resort Riviera Cancun By Karisma	Carr. Cancun-Pto.Morelos Km 27.5, Riviera Maya Bahia Petempich",
  "Azul Beach Resort Riviera Maya Hotel by Karisma	Km 27.5 Bahia Petempich, Riviera Maya Bahia Petempich",
  "Breathless Riviera Cancun Resort and Spa	Bahia Petempich Sm. 12 Mza. 41 Lote 2-04, Puerto Morelos",
  "Corales Suites	Ave. Javier Rojo Gomez Sm.2 Mz.13 Lt.1-4, Puerto Morelos",
  "Desire Rivera Maya Pearl Resort	Costera Norte, Lote 1, Mza. 26, Sm. 10 Puerto M., Puerto Morelos",
  "Desire Riviera Maya Resort	Carretera Pto. Morelos, Km. 27.5 S.M. 12 Mza. 41, Puerto Morelos",
  "Dreams Riviera Cancun Resort and Spa	Carretera Federal 307, Chetumal – Puerto Juarez, Puerto Morelos",
  "Grand Residences Riviera Cancun Resort	Boulevard El Cid Sm. 3 Mza. 2 Lote 4 y 5, Puerto Morelos",
  "Hacienda Morelos Beach Front Hotel	Avenida Rafael E Melgar Mz.2, Lt5-B Sm1, Puerto Morelos",
  "Hotel El Moro	Av. Javier Rojo Gomez SM 2 Mza 5 Lote 17, Puerto Morelos",
  "Hotel Marina El Cid Spa & Beach Resort	Blvd.El Cid Unidada 15, Puerto Morelos",
  "Hotel y Departamentos Eden	Av. Andres Quintana Roo #788 Mza.21 Sm.2, Puerto Morelos",
  "Kaam Accommodations	Sm 2 mz 8 lote 6 loc 2, Puerto Morelos",
  "Now Jade Riviera Cancun	Unidad 26 Mz. 20 Lote 1 - 1 Sm.3, Puerto Morelos",
  "Now Sapphire Riviera Cancun	Smza. 11Mza. 9 Lte 10, Puerto Morelos",
  "Ocean Coral and Turquesa - All Inclusive	Carr. Cancun- Playa del Carmen Lote 1-5 Sm12 Mz5, Puerto Morelos",
  "Ojo de Agua Beach Front Hotel	Av. Javier Rojo Gomez SM 2 Lote 16, Puerto Morelos",
  "Secrets Silversands Riviera Cancun	SM12 MZ31 Lote14-02, Puerto Morelos",
  "Vela's Condos	Sm.02 Mza.13 Lt.2-15, Puerto Morelos",
  "Ventus at Marina El Cid Spa & Beach Resort	Mza 20 Lt 1-01,Unidad 15 Sm 03, Puerto Morelos",
  "Zoetry Paraiso de la Bonita Riviera Maya	Km. 328 Carr. Chetumal-Cancun Pto. Morelos, Riviera Maya Bahia Petempich",
];

const hotelesPlayaDelCarmen = [
  "Aldea Thai Luxury Condohotel	Av. Cozumel Mza. 81 Lote 1, Playa del Carmen",
  "Allegro Playacar	Lote Hotelero No. 7 desarrollo playacar, Riviera Maya Playacar",
  "Ambassador at Grand Velas Riviera Maya	Carretera Cancun Tulum KM 62, Playa del Carmen",
  "A-Nah Suites	Av. 20 Norte Mza 86 Lt 02 entre calle 14 y 16 Nort, Playa del Carmen",
  "Andaz Mayakoba a Concept by Hyatt	Carretera Federal Cancun-Playa del Carmen Km.298, Playa del Carmen",
  "Artisan Senses Quinta Avenida	5A Avenida Norte No 324 entre 26 y 28 Norte, Playa del Carmen",
  "Aspira Hotel & Beach Club	Calle 16 entre Avenida 10 y Av. 15 Constituyente, Playa del Carmen",
  "Banana Boutique by GuruHotel	Calle 32 con Quinta Avenida, Playa del Carmen",
  "Banyan Tree Mayakoba	Carr. Fed. Chetumal - Pto. Juarez Km98, Playa del Carmen",
  "Barrio Latino	Calle 4 #153 entre Av. 10 y Av. 15, Playa del Carmen",
  "Be Playa	Ave. 10 esquina Calle 26, Playa del Carmen",
  "Beach House Hotel	1era Av. Norte entre las Calles 12 y 14, Playa del Carmen",
  "Blue Diamond Luxury Boutique Hotel - All Inclusive	Km.298 Carret. Fed.307, Playa del Carmen",
  "Blue Parrot Hotel 5th Avenue	5ª Avenida, Playa del Carmen",
  "BlueBay Grand Esmeralda - All Inclusive	Carr. Fed. Chetumal Km. 300, Riviera Maya Punta Bete",
  "Bric Hotel and Spa	Calle 28 entre av. 5 y 10, Playa del Carmen",
  "Caribbean Paradise Boutique by GuruHotel	5a. Avenida Esquina Av. Constituyentes, Playa del Carmen",
  "Casa Melissa	Av. Juarez M.1 Lt.4, Playa del Carmen",
  "Casa Ticul Boutique Hotel by Lux Hotels & Residences	5a Avenida, entre calle 38 y calle 40, lote 8, Playa del Carmen",
  "Catalonia Playa Maroma	Carretera Federal # 307, Riviera Maya Punta Maroma",
  "City Express Playa del Carmen	Mz.30 Lt.4 Fracc. Playacar FaseII, Riviera Maya Playacar",
  "City Suites Playa del Carmen	Av. Balamkanche Mza. 30 Lt 4, Playa del Carmen",
  "D'Angelos 5ta Avenida	5 Av Mza 4 entre C 34 y C 38 Nte L6, Playa del Carmen",
  "El Campanario	Av. 15 Norte No. 218 Esquina con calle 12, Playa del Carmen",
  "El Dorado Casitas Royale by Karisma	Carretera Cancun - Playa del Carmen, Riviera Maya Punta Brava",
  "El Dorado Maroma by Karisma	Carret. Cancun-Tulum, Riviera Maya Punta Maroma",
  "El Dorado Palafitos By Karisma	Carr.Fed.Tulum entre Marina Maroma y Zona Maritima, Riviera Maya Punta Maroma",
  "El Dorado Royale by Karisma	Carretera Cancun-Tulum KM 45, Solidaridad, Riviera Maya Punta Brava",
  "El Secreto Hotel by Bunik	Av. 5 entre calle 6 y 8, Playa del Carmen",
  "El Taj Ocean Front and Beachside Condo Hotel	1 Norte Esquina Calle 14 Norte, Playa del Carmen",
  "Encantada Condo	Calle 52 Mz. 289 Lt. 9 entre 1ra. y 5ta. Avenida, Playa del Carmen",
  "Eurostars Hacienda Vista Real	Paseo Xaman-Ha Ret.3 Lotes 12 y 13, Riviera Maya Playacar",
  "Fairmont Mayakoba	Carret. Federal Cancun-Playa del Carmen Km.298, Playa del Carmen",
  "Fairmont Mayakoba Inclusive	Carret. Federal Cancun-Playa del Carmen Km.298, Playa del Carmen",
  "Family Club Princess	Prolongacion 5ta Avenida Mza 20 Lote 006, Playa del Carmen",
  "Family Concierge at Paradisus La Esmeralda	5ta Avenida, esq. Calle 88, Lote 1 Mza. 569, Playa del Carmen",
  "Fiesta Inn Playa del Carmen	Av. 10 Esq. con Calle 26, Playa del Carmen",
  "Generations Riviera Maya By Karisma	Carr. Federal Cancun-Playa del Carmen Km.45 Muchim, Playa del Carmen",
  "Grand Class at Grand Velas Riviera Maya - Adults Only	Carretera Cancun-Tulum km 62, Playa del Carmen",
  "Grand Hyatt Playa del Carmen Resort	1a Av. Esquina Calle 26, Playa del Carmen",
  "Grand Riviera Princess All Suites Resort & Spa	Prolongacion 5ta Av. Mza 20 lt 006, Playa del Carmen",
  "Grand Velas Riviera Maya-Luxury All Inclusive	Carretera Cancun-Tulum Km. 62, Playa del Carmen",
  "Hacienda del Caribe	Calle 2 Norte entre la 10 Y 5a Avenida., Playa del Carmen",
  "Hacienda Paradise Boutique Hotel	Ave. 10 entre Calle 20 y 22, Playa del Carmen",
  "Hacienda Real Del Caribe	10 con Avenida 10, Playa del Carmen",
  "Hacienda Tres Rios	Carretera Cancun-Tulum Km.54, Riviera Maya Xcalacoco",
  "HM Playa del Carmen	Av. Constituyentes 180 x Calle 15 Norte y 20 Norte, Playa del Carmen",
  "Hotel El Punto Boutique and Beach Club	5ta Avenida y Calle 8, Playa del Carmen",
  "Hotel Lunata	5st ave nte entre calles 6 y 8 S/N, Playa del Carmen",
  "Hotel Maya del Mar	Calle 8 entre 5ta Avenida y ZFM, Playa del Carmen",
  "Hotel Thompson Playa del Carmen	5ta Avenida entre calles 12 y 14, Playa del Carmen",
  "Hotel Xcaret Mexico - All Parks and Tours / All Fun Inclusive	Carretera Chetumal-Puerto Juarez km 282, Riviera Maya Xcaret",
  "Hotelito del Mar By Xperience Hotels	20 Avenida Nte. y calle 40 Nte., Playa del Carmen",
  "Iberostar Grand Hotel Paraiso	Carrt. Chetumal-Pto Juarez km 309, Riviera Maya Playa Paraiso",
  "Iberostar Paraiso Beach	Riviera Maya, km. 309, Riviera Maya Playa Paraiso",
  "Iberostar Paraiso del Mar	Carretera Chetumal - Puerto Juarez km 309, Riviera Maya Playa Paraiso",
  "Iberostar Quetzal	Avenida Xaman-Ha Lote 2, Fraccionamiento Hotelera, Riviera Maya Playacar",
  "Iberostar Selection Paraiso Lindo	Carrt. Chetumal-Pto. Juarez km. 309, Riviera Maya Playa Paraiso",
  "Iberostar Selection Paraiso Maya	Carrt. Chetumal-Pto Juarez km 309, Riviera Maya Playa Paraiso",
  "Iberostar Tucan	Ave. Xaman Ha Lote Hotelero, Playa del Carmen",
  "Ikonik The Carmen Hotel - Adults Only	Calle 8 norte manzana 4, Playa del Carmen",
  "In Fashion Hotel and Spa	Calle 12 Norte S/N centro Gonzalo Guerrero, Playa del Carmen",
  "It Residences by Sercotel	Calle 44 con Avenida Primera- Zazil-Ha, Playa del Carmen",
  "Kinbe	Calle 10 Norte entre 1 y 5 Avenida., Playa del Carmen",
  "KLR The City Condos By Sercotel	Av. Constituyentes esquina Calle 25 Norte, Playa del Carmen",
  "Koox City Garden Hotel	Avenida 5 Norte Mza. 53 Lote 3, Playa del Carmen",
  "Koox Downtown Family Boutique Hotel	Avenida 10 Esquina Calle 26, Playa del Carmen",
  "Koox La Mar Condhotel	Calle 1 Norte Ocean Plaza, Playa del Carmen",
  "Koox Moma 42 Condhotel	Calle 42 Edif Terramar Interior 2do Piso, Playa del Carmen",
  "La Galeria by Bunik	Av. 30 con calle 20 Mz.26 lote.1 C.P.77710, Playa del Carmen",
  "La Pasion Hotel Boutique by Bunik	Calle 10 entre Avenidas 15 y 20, Playa del Carmen",
  "La Reina Roja Hotel Boutique	Calle 20 Nte, Playa del Carmen",
  "Las Golondrinas	Av. Constituyente No. 178 entre 15 y 20., Playa del Carmen",
  "Las Palapas	Av. 34 Norte s/n, 5a. Av. y Zona Federal Maritima, Playa del Carmen",
  "Las Perlas Condo	Calle 50 entre 1ra y 5ta Avenida, Playa del Carmen",
  "Le Reve Boutique BeachFront Hotel	Playa Xcalacoco Fraccion 2A, Playa del Carmen",
  "Live Aqua Boutique Resort Playa del Carmen	Quinta Avenida Esquina Calle 32, Playa del Carmen",
  "Magic Blue Spa Boutique Hotel Adults Only	Avenida 10 y Calle 12, Playa del Carmen",
  "Mahekal Beach Front Resort & Spa	Calle 38 y Zona Federal Maritima, Playa del Carmen",
  "Maya Villa Condo Hotel and Beach Club	1a av. norte Mza. 26, #23, Esq. Calle 16bis, Playa del Carmen",
  "Newport House Playa	Av. 10 Norte Entre calle 44 y 42, Playa del Carmen",
  "Nina Hotel & Beach Club	Calle 6 Norte entre 10 y 15 Av, Playa del Carmen",
  "Occidental at Xcaret Destination	Carretera Federal 307 Chetumal - Puerto Juarez Km., Riviera Maya Xcaret",
  "Ocean Maya Royale Solo Adultos All Inclusive	Carretera Fed. Chetumal, Km. 299, Riviera Maya Punta Bete",
  "Ocean Riviera Paradise All Inclusive	Carr. Fed. Km 296, Predio Montecarlos y Punta Bete, Playa del Carmen",
  "Ocean Riviera Paradise El Beso - Adults Only	Carr. Fed. Km 296, Predio Montecarlos y Punta Bete, Playa del Carmen",
  "Opal Suites	Calle 38 Norte Mz 124 Lt 9, Playa del Carmen",
  "Panama Jack Resorts Gran Porto Playa del Carmen	AV. CONSTITUYENTES No. 1, Playa del Carmen",
  "Paradisus Playa del Carmen La Esmeralda	5ta Avenida, esq. Calle 88, Lote 1 Mza. 569, Playa del Carmen",
  "Paradisus Playa del Carmen La Perla	5ta Avenida, exq. Calle 88, Lote 1, Mza. 569, Playa del Carmen",
  "Platinum Yucatan Princess All Suites and Spa Resort Adults Only	Prolongacion 5ta Av. Mza.20 lt.006, Playa del Carmen",
  "Playa Palms Beach Hotel	1A Av. Nte. Zona Federal maritima Mxa. 023, Playa del Carmen",
  "Playacar Palace	Fraccionamiento Playacar KM 62.5, Riviera Maya Playacar",
  "Porto Playa Condo Hotel and Beach Club	1ª Av. Norte Mza 26#23 Esquina Calle 16 Bis, Playa del Carmen",
  "Pueblito Luxury Condohotel	38 Norte Mz 08 Lte 02 Local 5, Playa del Carmen",
  "Pure All Suites Riviera Maya	Carretera Federal Puerto Juarez Km 294+700, Playa del Carmen",
  "Pure Mareazul - Playa del Carmen	Carretera Federal 307 Cancun- Chetumal KM 294 7, Playa del Carmen",
  "Residences at The Fives	Xcalacoco El Limonar 1, Playa del Carmen",
  "Riu Lupita	Lote Hotelero No. 1, Manzana 20 Desarollo Playacar, Riviera Maya Playacar",
  "Riu Palace Mexico	Avda. Xaman-Ha, Manzana 3, Lote 4, Condominio, Riviera Maya Playacar",
  "Riu Palace Riviera Maya	Av.Xaman-Ha Mza.9 y 10 Lote 1, Riviera Maya Playacar",
  "Riu Playacar	Avenida Xaman-Ha, Manzana 6, Lote 6, Riviera Maya Playacar",
  "Riu Yucatan	Ave. Xaman-Ha, MZ 3 L 1. Condominios Playacar, Riviera Maya Playacar",
  "RiuTequila	Paseo Xaman-Ha Mz25, Playacar, Km 62.5, Riviera Maya Playacar",
  "Riviera Caribe Maya	Av. 10 Nte. Esq. Calle 30 Lt.8 Mz.61 Municipio Sol, Playa del Carmen",
  "Royal Hideaway Playacar Adults Only	Lote Hotelero No.6, Mza. 6, Riviera Maya Playacar",
  "Royal Service at Paradisus La Perla	5ta Avenida, exq. Calle 112, Lote 1, Mza. 569, Playa del Carmen",
  "Sandos Caracol Eco Resort All Inclusive	Carretera Cancun - Tulum, Playa del Carmen Km. 295, Playa del Carmen",
  "Sandos Caracol Eco Resort Select Club All Inclusive	carretera chetumal pto juarez km 295, Playa del Carmen",
  "Sandos Playacar All Inclusive	Paseo Xaman Ha Lt.1, Mza. 1, Riviera Maya Playacar",
  "Sandos Playacar Beach Resort Select Club All Inclusive	Paseo Xaman Ha Lt.1, Mza. 1, Riviera Maya Playacar",
  "Secrets Capri Riviera Cancun	Carr. Chetumal- Pto. Juarez Km 299, Riviera Maya Punta Bete",
  "Secrets Maroma Beach Riviera Cancun	Carretera Federal 307 Chetumal-Cancun Km, 306.5, Riviera Maya Punta Maroma",
  "Select Inn Quinta Playa del Carmen	Av. CTM (Calle 46), Mza 258, Lote I, Playa del Carmen",
  "Senses Riviera Maya by Artisan – Gourmet All Inclusive - Adults Only	Carretera Chetumal- Cancun Km 307 Lote 71 y 72, Riviera Maya Playa Paraiso",
  "Soho Playa	10 Avenida Norte con Calle 24 Norte, Playa del Carmen",
  "Soul Beach Hotel and Spa	Calle 28 Entre10 ma y5ta Av, Playa del Carmen",
  "Studio 30 Condhotel	Avenida 30, entre Calle 6 y 8. Numero 160, Playa del Carmen",
  "Suites Quinto Sol	5ta. Avenida norte esquina Calle 28 norte., Playa del Carmen",
  "Sunrise 42 Suites Hotel	42 Entre 5ta y 10ma Avenida, Playa del Carmen",
  "Sunset Fishermen Beach Resort Playa del Carmen	Bahia del Espiritu Santo No. 9, Riviera Maya Playacar",
  "The Fives Beach Hotel & Residences All Senses Inclusive	Predio El Limonar Fraccion 2, Riviera Maya Xcalacoco",
  "The Fives Downtown Hotel and Residences, A Curio Collection by Hilton	Calle 10 con 2, Playa del Carmen",
  "The Magic Hotel	Calle 54 Norte entre Diagonal 55 Norte y 50 Pte, Playa del Carmen",
  "The Palm at Playa	Calle 8 entre 10ma y 5ta Avenidas, Playa del Carmen",
  "The Reef 28 Adults Only All Suites	1 Avenida Nte y Calle 28 Nte, Playa del Carmen",
  "The Reef Coco Beach	Region 6, Calle Flamingo Lt 1 Mz 7, Playa del Carmen",
  "The Reef Playacar	Paseo Xaman - Ha s/n,, Riviera Maya Playacar",
  "The Royal Haciendas Resort & Spa All Inclusive	Chetumal Pto. Juarez Highway Km 289+10 Lote 2 Mz70, Playa del Carmen",
  "THE Royal Playa del Carmen	Constituyentes No. 2, Playa del Carmen",
  "Tukan Hotel & Beach Club	5ta. Avenida Norte entre 14 y 16, Playa del Carmen",
  "Unic Design Hotel	Quinta Avenida entre calles 24 y 22, Playa del Carmen",
  "Valentin Imperial Riviera Maya	Carretera Fed. Cancun Tulum KM 311, Riviera Maya Playa del Secreto",
  "Viceroy Riviera Maya	Xcalococo, Riviera Maya Xcalacoco",
  "Villas Sacbe Condo Hotel and Beach Club	1ª Av. Norte Mza.26#23 Esquina Calle 16 BIS, Playa del Carmen",
  "Viva Wyndham Azteca	Xaman Ha Mza 8 Lote 1, Riviera Maya Playacar",
  "Viva Wyndham Maya	Paseo Xaman - Ha Lote Hotelero 5,, Riviera Maya Playacar",
  "Wyndham Garden Playa del Carmen	Lote 5 y 6 Mza 29 Condominio Playacar, Playa del Carmen",
  "Xtudio Comfort Hotel by Xperience Hotels - 5th Avenue	5ta Avenida entre Calle 4 y 6, Playa del Carmen",
];

const hotelesPuertoAventuras = [
  "Aventuras Club Lagoon and All Suites Resort	Av. Xcacel, # 7, (Plano 1,2,3 y 4), Riviera Maya Puerto Aventuras",
  "Aventuras Club Marina	Bahia Xcacel #7 Mza 32 Lotes 1, 2, 3 y 4, Riviera Maya Puerto Aventuras",
  "Barcelo Maya Beach	Carret. Chetumal-Puerto Juarez Km. 266.3, Riviera Maya Xpu Ha",
  "Barcelo Maya Caribe	Ctra. Federal Chetumal-Puerto Juarez Km. 266,3, Riviera Maya Xpu Ha",
  "Barcelo Maya Colonial	Ctra. Federal Chetumal - Puerto Juarez, Km 266.3, Riviera Maya Xpu Ha",
  "Barcelo Maya Palace	Ctra. Federal Chetumal-Puerto Juarez Km. 266,3, Riviera Maya Xpu Ha",
  "Barcelo Maya Tropical	Carr. Chetumal Pto Juarez km 266.3, Riviera Maya Xpu Ha",
  "Bel Air Collection Resort and Spa Riviera Maya	Carretera Chetumal-Puerto Juarez Km. 265, Riviera Maya Xpu Ha",
  "Catalonia Riviera Maya	Av. Xcacel, Puerto Aventuras Lote1 Mza. 18/Plano 2, Riviera Maya Puerto Aventuras",
  "Catalonia Royal Tulum	Carretera Cancun- Chetumal Km. 264,5 Xpu-Ha, Riviera Maya Xpu Ha",
  "Catalonia Yucatan Beach	Xcacel, Riviera Maya Puerto Aventuras",
  "Coral Maya Turquesa Condo Hotel	Bahia Kantenah # 38, Riviera Maya Puerto Aventuras",
  "Dreams Puerto Aventuras	Km 269 Carretera Chetumal Pto, Riviera Maya Puerto Aventuras",
  "Hard Rock Hotel Riviera Maya	Carretera Cancun-Tulum Km. 72, Riviera Maya Puerto Aventuras",
  "Heaven en Hard Rock Hotel Riviera Maya	Carretera Cancun-Tulum Km. 72, Riviera Maya Puerto Aventuras",
  "LM by Inmense	Punta Matzoma No. 23 y 33, Mza 24, Plano 3, Riviera Maya Puerto Aventuras",
  "Omni Puerto Aventuras	Km. 269.5 Carretera Chetumal - Puerto Juarez, Riviera Maya Puerto Aventuras",
  "Serenity Eco Luxury Tented Camp By Xperience Hotels	Carretera Federal Xpu-Ha km 265 Lt 6, Riviera Maya Xpu Ha",
];

const hotelesAkumal = [
  "Akumal Bay Beach and Wellness Resort	Carretera Federal Chetumal, Benito Juarez, Km. 254, Riviera Maya Akumal",
  "Akumal Natura	Camino de acceso a Uxuxubi con Torres Alta Tension, Riviera Maya Akumal",
  "Bahia Principe Grand Coba	Ctra. Chetumal-Cancun km. 250, Riviera Maya Akumal",
  "Bahia Principe Grand Tulum	Ctra. Chetumal-Cancun km. 250, Riviera Maya Akumal",
  "Bahia Principe Luxury Akumal	Carretera Chetumal-Cancun km. 250, Riviera Maya Akumal",
  "Bahia Principe Luxury Sian Ka'an Adults Only	Carretera Chetumal Km. 250, Riviera Maya Akumal",
  "El Dorado Seaside Palms, By Karisma	Carretera Playa del Carmen-Tulum km 95, Riviera Maya Kantenah",
  "El Dorado Seaside Suite Infinity, By Karisma	Km. 45 Carr. Cancun Tulum Punta Brava, Riviera Maya Kantenah",
  "Grand Oasis Tulum	Km. 251 Carretera Federal Chetumal-Puerto Juarez, Riviera Maya Akumal",
  "Grand Palladium Colonial Resort and Spa	Carretera Chetumal-Puerto Juarez Km, 256-100, Riviera Maya Kantenah",
  "Grand Palladium Kantenah Resort and Spa	Carretera Chetumal-Puerto Juarez Km, 256-100, Riviera Maya Akumal",
  "Grand Palladium White Sand Resort and Spa	Carretera Chetumal-Puerto Juarez Km, 256-100, Riviera Maya Kantenah",
  "Grand Sirenis Riviera Maya Resort & Spa – All Inclusive	Carretera Federal Cancun-Tulum Km. 256.3, Riviera Maya Akumal",
  "Hidden Beach Resort Au Naturel, By Karisma	Km 95 Carretera Cancun, Riviera Maya Kantenah",
  "Las Villas Akumal	Carr. Cancun-Tulum Km. 104 Mza. 11 Lt. 1, Riviera Maya Akumal",
  "Oasis Tulum Lite	Km. 251 Carretera Federal Chetumal-Puerto Juarez, Riviera Maya Akumal",
  "The Sian Ka'an at Grand Tulum	Carretera Chetumal Puerto Juarez Km. 252, Riviera Maya Akumal",
  "TRS Yucatan Hotel Solo Adultos	Carretera Chetumal-Puerto Juarez Km, 256-100, Riviera Maya Kantenah",
  "Unico 20° 87° Hotel Riviera Maya	Carretera federal 307. Km. 260, Manzana 22, Riviera Maya Kantenah",
  "Secrets Akumal Riviera Maya	Carretera Federal 307 Chetumal-Puerto Juarez Km254, Tulum",
];

const hotelesTulum = [
  "Ahau Htl Tulum	Carr. Tulum a, Av. Boca Paila Km. 7.5, Zona Costera, 77760 Tulum, Q.R.",
  "Amansala Yoga & Wellness Resort Tulum	Carretera Boca Paila Km. 5.5, 77780 Tulum, Mexico",
  "Ana y Jose Hotel & Spa Tulum	A 7 km. Al sur de las Ruinas de Tulum, Tulum )",
  "Azucar hotel Tulum	Carretera Boca Paila km. 7.5 de la Zona Hotelera Tulum",
  "Azul Tulum	Calle Sayil, 77780 Tulum, Q.R., Mexico",
  "Azulik Tulum	 Carretera Tulum - Punta Allen KM 5, Zona Hotelera, 77780 Tulum, Q.R.",
  "Be Tulum Beach & Spa Resort	Carretera Tulum-Boca Paila Km. 10, Tulum )",
  "Boca Paila Camps by Cesiak	Carretera Tulum - Punta Allen Km 25 Punta Allen, 77780 Tulum, Q.R.",
  "Cabanas Los Lirios	Carretera Boca Paila km 7.5, Tulum )",
  "Cabañas Copal Tulum	Carr. Tulum Ruinas KM. 5 Tulum, Quintana Roo",
  "Cabañas Tulum	Carretera Tulum - Bocapaila Km 7, Tulum )",
  "Casa Amor Del Sol	Carretera Tulum, s/n, Lote 3 A, Norte Paraiso Tankah, Tulum, Q.R.",
  "Casa Corazon Cabañas	Privada Bahia Soliman, Quintana Roo",
  "Coco Tulum	Carretera Boca Paila km 8 Tulum, Quintana Roo",
  "Dreams Tulum Resort & Spa	Riviera Maya Km. 234, Tulum )",
  "El Paraiso Hotel Restaurant bar-lauge & Beach Club Tulum	Carretera Boca Paila Mz 3 Tulum Ruinas, 77780 Tulum, Q.R.",
  "Grand Oasis Tulum	Carretera Chetumal, Puerto Juarez Km 252, Juarez, 77780 Akumal, Q.R.",
  "Green Tulum	Av. Coba Lote 4 Mza 37, Tulum )",
  "Hemingway Eco	Carretera Tulum-Boca Paila km 6.5, Tulum Beach, 77780 Tulum, Q.R.",
  "Hip Hotel Tulum	Carretera Tulum-Boca Paila KM 8, Tulum Beach, Zona Hotelera, 77780 Tulum, Q.R.",
  "Hotel Kin-Ha	Calle Orion Sur, entre Sol y Venus, Centro, 77780 Tulum, Quintana Roo, Mexico",
  "Hotel Posada 06 Tulum	Andromeda Ote, Tulum Centro, Col Huracanes, 77780 Tulum, Q.R.",
  "Hotel Tulum Inn	Av. Zamna Mz 32 L-4 A entre Kukulcan e Xcaret, Tulum )",
  "Hotel Zulum	Carretera Tulum-Boca Paila km 6.5, Tulum )",
  "Hotelito Azul	Carreta Tulum-Boca Paila, KM 5.8 Tulum",
  "Kore Tulum Retreat & Spa Resort	Carretera Tulum Boca Paila Km 3.8 Lt 48, Tulum )",
  "La Vita E Bella Tulum	Carretera Tulum a, Av. Boca Paila Km. 1.5, Zona Hotelera, 77780 Tulum, Q.R.",
  "La Zebra Beach Hotel & Restaurant	Carretera Tulum-Boca Paila Km 8.2, Tulum Beach, Zona Costera, 77780 Tulum, Q.R.",
  "Las Ranitas Eco Boutique	Carretera Tulum Boca-paila km 9 Zona Hotelera. C.P. 77780,, Tulum, Q.R.",
  "Lo Nuestro Petit	Av. Osiris Sur Mz 42, Lote 12, Centro, 77760 Tulum, Q.R.",
  "Luna Llena Boutique Hotel	Calle 6 sur entre 9 y 7 sur Col. La Veleta Tulum, Quintana Roo",
  "Luv Tulum	Carr. Tulum-Boca Paila, Tulum Beach, 77780 Q.R.",
  "Maison Tulum Hotel	Calle MZ 13 Lote 4 Norte Centro, Alfa, 77780 Tulum, Q.R.",
  "Mestizo Hotel Boutique	Av. Coba mz 36 LT 4 Y 5, Tulum Centro, Centro, 77780 Tulum, Q.R.",
  "Nueva Vida de Ramiro Tulum	Carretera Tulum-Boca Paila Km 8.5, Tulum Beach, 77780 Tulum, Q.R.",
  "Om Tulum	Carratera Tulum-Punta Allen km 9.5, 77780 Tulum",
  "Palms Tulum Luxury Hotel	Escorpion Sur esquina con Andromeda Oriente, Tulum )",
  "Papaya Playa	Km 4.5 Carr. Tulum - Boca Paila, Tulum )",
  "Pavoreal Beach Resort	Carretera Cancun-Tulum km.237, Tulum )",
  "Posada Punta Piedra	CARRETTERA KM 4 TULUM, Av. Boca Paila, 77780 Tulum, Q.R.",
  "Posada Yum Kin Hotel	Avenida Kukulcan Norte Manzana & Lote 8 403, 77760 Tulum, Q.R.",
  "Retiro Maya 	Carretera Tulum-Boca Paila Km 6.5 Tulum Beach  Q.R.",
  "Rosa del Viento Hotel & Resort	Carretera Boca Paila KM. 10 Tulum, Quintana Roo",
  "Secret Garden Hotel	Calle Sagitario Pte. 54, Tulum Centro, Laureles, 77780 Tulum, Q.R.",
  "The Beach Tulum Hotel	Carreera Tulum-Boca Paila KM 7, Tulum Beach, Zona Hotelera, 77780 Tulum, Q.R.",
  "Bahia Principe Luxury Sian Kaàn	Carretera Chetumal - Cancun Km 250. Mexico",
  "Tulumbay Hotel	Carretera Tulum Ruinas Boca Paila km 5, 77760 Tulum, Q.R.",
  "Xcaret Hotel	Carretera Federal Chetumal-Puerto Juarez, Av. Solidaridad 2, 77710 Playa del Carmen, Q.R.",
  "Xibalba Hotel Tulum	Avenida Andromeda Oriente Manzana 7 Lote 7,Tulum, Mexico",
  "Zahra Tulum	Carretera Tulum Ruinas Km. 5, Tulum, Mexico",
  "Zamas Tulum Boutique Beach Hotel & Restaurant	KM 5 Carretera Tulum-Boca Paila, Tulum, Q. Roo 77780",
];

// const fromAeropuertoCancun = correctCase(fromAeropuertoCancunNotFormatted);
const hotelesMeridaAeropuerto = [
  "Hacienda Tepich	Carretera Merida - Z.A Mayapan-Chetumal Entrada km 5.8 Tepich, Acanceh, Yucatan, C.P. 97382",
  "Hotel Boutique Sercotel Casona 61	Calle 61 527 Por  66 y 68, Centro, 97000 Merida, Yuc.",
  "Hacienda Santa Cruz	Calle 86 S/N, Santa Cruz Palomeque, 97315 Merida, Yuc.  ",
  "Koox Naluum Eco Hotel	Salida a Cancun desviacion Carretera Merida-Chetumal km.22.9, libramiento, 97820 Tecoh",
  "Hotel Hacienda Inn Aeropuerto	Av. Aviacion No. 709 Col. Sambula, Merida, Yucatan 97259 Mexico",
  "Koox Art 64 Boutique Hotel	Calle 64 Numero 446 por 53 y 49 Centro, 97000 Merida, Yuc.",
  "Hotel del Peregrino	Calle 51 Numero 488 Por 54 y 56, col. Centro, Merida, Yucatan, Mexico",
];

const hotelesMeridaCentro = [
  "Hotel Boutique Ya'ax	Calle 57 461, Parque de la Mejorada, Centro, 97000 Merida, Yuc.",
  "Hostal Akasha 	Calle 47 479, Zona Paseo Montejo, Centro, 97000 Merida, Yuc.",
  "Los Aluxes	Calle 60 No. 444 por 49, Merida Centro",
  "Ambassador	Calle 59 546, Parque Santiago, Centro, 97000 Merida, Yuc.",
  "Hotel Maya Yucatan	Calle 58 Numero 483 por 55 Y 57 Centro Historico, Merida",
  "Boulevard Infante	Av. Itzaes 587, Centro, 97259 Merida, Yuc.",
  "Hotel Caribe	Calle 59 x 60 #500, a un rincon del Parque Hidalgo, Centro Historico",
  "Casa Azul Hotel Boutique	Calle 60 343, Centro, 97000 Centro, Yuc.",
  "Casa Carmita	Calle 53 515A x 62 y 64, Centro, 97000 Merida, Yuc.",
  "Casa Continental 	Calle 47 No. 480 x 56 Yucatan, Centro, 97000 Merida, Yuc.",
  "Casa de las Columnas	Calle 59 #636 Por 80 Y 82 Centro Historico, 97200, Merida, Yucatan, Mexico",
  "Koox hotel Casa de las Palomas	Calle 64ᴬ 417, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Casa del Balam	Calle 60 #488 x 57, Centro Historico, Merida, Yucatan, Mexico",
  "Casa Fernanda	Calle 57 472, Parque de la Mejorada, Centro, 97000, Yuc.",
  "Hotel Casa Lecanda Boutique	Calle 47 #471, Por la 54 y 56 Centro, 97000 Merida, Yuc.",
  "Hotel Casa Lucia Boitique	Calle 60 474 A, 53, Calle 55 Col, Centro, 97000 Merida, Yuc.",
  "Casa Nobel	Calle 72, (Avenida Reforma) N° 403-C cruzamiento 39 y 41, Merida Yucatan Mexico.",
  "Hostal Catedral	Entre 60 y 58, Calle 61 499 Altos, Centro, 97000 Merida, Yuc.",
  "El Cid	Calle 61 # 573 A x 74 y 76, Centro, 97000 Merida, Yuc.",
  "Hotel Colon 	Calle 62 483, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Colonial	Calle 62 476, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Los Arcos	Calle 63 No. 501, Centro, 97000 Merida, Yuc.",
  "Hotel Las Dalias Inn	Calle 57 x 48 y 50 No. 435, Centro, 97000 Merida, Yuc.",
  "Hotel del Gobernador	Calle 59 #535 x 66, Centro, 97000 Merida, Yuc.",
  "Hotel Del Parque	Calle 60 #495, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Del Peregrino	Calle 51 488 X 56 & 54, Centro, Merida, Yucatan, Mexico, 97000 Merida",
  "Doralba Inn	Calle 63 464, Centro, 97000 Centro, Yuc.",
  "Hotel Eclipse	Calle 57 491, Parque Santa Lucia, Centro, 97000 Centro, Yuc.",
  "Hotel Embajadores	Calle 61 534, Parque Santiago, Centro, 97000 Merida, Yuc.",
  "Hotel Español	Calle 69 543, Centro, 97000 Merida, Yuc.",
  "Hotel Flamingo	Calle 57, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Gama de Fiesta Inn Castellano	Calle 57 NO. 513 62 x 64, Centro, 97000 Merida, Yuc.",
  "Gran Centenario	Calle 55 #513 Por 60 y 62, Centro, 97000 Merida, Yuc.",
  "Gran Hotel Merida	Calle 60 496, Centro, 97000 Merida, Yuc.",
  "Gran Real Yucatan	Calle 56 474, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel H. O.	Calle 62 515 x 65 y 67, Centro, 97121 Merida, Yuc.",
  "Hotel Hacienda Merida	Calle 62 #441- A x 51 y 53 Col.Centro C.P. 97050 Merida, Yucatan Mexico.",
  "Holiday Inn Express Centro	Calle 60 No. 491, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Koox Art 57	Calle 57 543, Barrio de Santiago, Centro, 97000 Merida, Yuc.",
  "Koox Art 64	 calle 64 # 446 por 53 y 49, 97000 Merida, Yuc.",
  "Koox Casona de las 3 Marias	Calle 64 428 x 53 y 49 Centro Historico, 97000 Merida, Yuc.",
  "Hostel Le Juj	calle 59 596 A entre 74 y, Calle 59 76, Centro, 97000 Merida, Yuc.",
  "Hostal Luz de Yucatan	Calle 55 499 x 60 y 58, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Maison del Embasador	Calle 60 #472 x 53 y 55 Centro Historic, 97000 Merida, Yuc.",
  "Mansion Lavanda	Calle 64ᴬ 547, Centro, 97000 Merida, Yuc.",
  "mansion Merida	Entre calle 58-60 Centro Yucatan, Calle 59 498, Centro, 97000 Merida, Yuc",
  "Maria del Carmen	 Calle 63 550, Parque Santiago, Centro, 97000 Merida, Yuc.",
  "Maria Jose	Calle 64 #456 Por 53 y 55, Centro, 97000 Merida, Yuc.",
  "Hotel Marionetas	Calle 49 No. 516, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Medio Mundo	Calle 55 533, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Mejorada Merida	Por 50 y 52, Calle 59 434, Centro, 97000 Merida, Yuc.",
  "Hotel Merida	Calle 60 entre 55 y 57 #491-B Col. Centro, 97000, Merida, Yucatan, Mexico",
  "Hotel Merida Santiago	Calle 74-A #499, x 57 y 59-A, Calle 74A, Centro, 97000 Merida, Yuc.",
  "Hotel Meridiano	Calle 54 478, Parque de la Mejorada, Centro, 97000 Merida, Yuc.",
  "Mision de Fray Diego	Calle 61 #524 x 64 y 66, Centro, 97000 Merida, Yuc.",
  "Mision Panamericana	Calle 59 455 por 52 y 54, Centro, 97000 Merida, Yuc.",
  "Hotel Montejo	57 507 Entre calles 62 y 64, Centro, 97000 Merida, Yuc.",
  "Hotel Mucuy	Calle 57 481, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Nacional Merida	Calle 61 474, Centro, 97000 Merida, Yuc.",
  "Hostel Nomandas	Calle 62 433, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel Paris	entre 57 y 55 97000, Calle 68 474, 97000 Merida, Yuc.",
  "Hotel Piazzetta	Calle 50-A 493A, Parque de la Mejorada, Centro, 97000 Centro, Yuc.",
  "Hotel Piedra de Agua	Calle 60 496, Centro, 97000 Merida, Yuc.",
  "Hotel Plaza Mirador	Calle 70 #541A x 67, 97000 Merida, Yuc.",
  "Posada Toledo	Calle 58 No 487 x 57, Centro, 97000 Merida, Yuc.",
  "Real San Juan Center	Calle 62 No. 309-E x calle 33 B Y 33 C, Centro, 97000 Merida, Yuc.",
  "Hotel Reforma	Centro, 97000 Merida, Yuc.",
  "Hotel San Jose	Calle 63 503-G, Centro, 97000 Merida, Yuc.",
  "Hotel San Juan	Calle 55 497, Parque Santa Lucia, Centro, 97000 Merida, Yuc.",
  "Hotel San Patricio	Calle 57 474 C, Parque de la Mejorada, Centro, 97000 Merida, Yuc.",
  "Hotel Santa Ana	Calle 45 # 503 X 60 y 62, Centro, 97000 Merida, Yuc.",
  "Hotel Santa Lucia	Calle 55 No. 508 entre 60 y 62 Colonia Centro, C.P. 97000",
  "Hotel Santa Maria	Calle 55 493 x 56 y 58, Centro, 97000 Merida, Yuc.",
  "Hotel Santiago	 Calle 62 NO.464 X 55 y 57 Col. Centro Merida, Yucatan",
  "Hostel Siesta Fiesta	Calle 60 Calle 51 & Centro, 97000 Merida, Yuc.",
  "Tierra del Sol	Calle 69 Num.570-B esq. 72, 97000 Merida, Yuc.",
  "Hotel Viva Merida	Calle 59 553, Parque Santiago, Centro, 97000 Merida, Yuc.",
  "Hostal Xiinbal	Calle 70 esquina con 65 #561 Antiguo Barrio de Santiago Col Centro,",
  "Hostal Zocalo	Calle 63 508, Centro, 97000 Merida, Yuc.",
];

const hotelesMeridaSegundoCuadro = [
  "Rosas & Xocolate Boutique Hotel Spa	Paseo de Montejo 480, Zona Paseo Montejo, Centro, 97000 Merida, Yuc.",
  "Hotel Las Americas	Calle 35 # 494 x 54 y 56, Centro, 97144 Merida",
  "Casa Italia	Calle 52 411D, Centro, 97000 Merida, Yuc.",
  "Casa Palomino	Calle 60 374, Zona Paseo Montejo, Centro, 97000 Centro, Yuc.",
  "City Express Plus	Calle 60 Numero 346, Zona Paseo Montejo, Centro, 97000 Merida, Yuc.",
  "El Conquistador	Paseo de Montejo 458, Zona Paseo Montejo, Centro, 97000 Merida, Yuc.",
  "Hotel Downtown Merida	Calle 62 295A, Alcala Martin, 97050 Merida, Yuc.",
  "Hotel Español Paseo Montejo	Paseo de Montejo 484, Zona Paseo Montejo, Centro, 97000 Merida, Yuc.",
  "Fiesta Americana Merida	Paseo Montejo No. 451, esq, Av. Colon, Centro, 97000 Merida, Yuc.",
  "Hotel Suites Flamboyanes	Av. Itzaes 266, Garcia Gineres, 97070 Merida, Yuc.",
  "Holiday Inn Merida	Av. Colon 498 Entre Paseo Montejo Y Calle 60, 97000 Merida, Yuc.",
  "Hotel Holly Merida	Calle 37 No.480 x Calle 54 y Calle 56, Centro, 97000 Merida, Yuc.",
  "Hyatt Regency Merida	Av. Colon esq. Calle 60 a 100 mts. de Paseo de Montejo, Merida, Mexico, 97000",
  "Ibis Merida	Av Carlos Torre Repetto 495, Centro, 97000 Merida, Yuc.",
  "Hotel Las Margaritas	Calle 27 # 220A por 30 Y 32, Garcia Gineres, 97070 Merida, Yuc.",
  "El Marques Merida	Calle 54 No. 373 G x 33-a y 35, Centro, 97000 Merida, Yuc.",
  "Hotel Mody Merida	Av Itzaes 243 x 27 Col. Garcia Gineres, Merida 97000 Mexico",
  "NH Collection Merida	Calle 60 346, Zona Paseo Montejo, Centro, 97000 Merida, Yuc.",
  "Palacio Maya Merida	Calle 62 327, Centro, 97000 Centro, Yuc.",
  "Posada Real Mercedes	Av. Itzaes No. 261 x 29 y 31, Garcia Gineres, 97070 Merida, Yuc.",
  "Presidente Intercontinental Villa Mercedes	Av. Colon 500, Centro, 97000 Merida, Yuc.",
  "Real San Juan Boutique	Calle 62 No. 309-E x calle 33 B Y 33 C, Centro, 97000 Merida, Yuc.",
  "Hotel Residencial	Calle 59 589, Barrio de Santiago, Centro, 97000 Merida, Yuc.",
  "Capital o Suites del Sol	Calle 58 #405 x 39 y 41, Centro, 97000 Merida, Yuc.",
  "Tecnohotel Itzaes	Calle 86 No. 444-B col. Centro cp. 97000 Merida, Yucatan, MX.",
  "The Diplomat Hotel Boutique	Calle 78 493A, Barrio de Santiago, Centro, 97000 Merida, Yuc.",
  "The Villa Merida	Calle 59 615-A x 80 y 82, Centro, 97000 Merida, Yuc.",
  "Hotel Victoria	Paseo de Montejo 438, Centro, 97000 Merida, Yuc.",
  "Wyndham Merida	Avenida Colon Esquina con la Calle 6, Garcia Gineres, 97000 Merida, Yuc.",
  "Hotel Zamna	Calle 53 #547 entre 70 y 72 Colonia Centro C.P. 97000",
];

const hotelesMeridaColonias = [
  "Delfina Hotel Boutique	Prol. Paseo de Montejo No.481 x 17-A Fracc, Montejo, 97127 Merida, Yuc.",
  "City Express Merida	Av Prol. Paseo Montejo No. 332, Benito Juarez Nte., 97119 Merida, Yuc.",
  "Hotel Las Cruces	Calle 60 Norte #388-I Por Calle 27 y Calle 29, Alcala Martin, 97050 Merida, Yuc",
  "Fiesta Inn	Calle 5 B No. 290 A x 20 A y 60, Col Revolucion. Mexico, Calle 60, 97115 Merida, Yuc.",
  "Hacienda Misne	Calle 19 172, Colinia Misne, 97173 Merida, Yuc.",
  "Hampton Inn by Hilton	Calle 20-A numero 288, Por 5-a Colonia Xcumpich, Merida, Yucatan, 97204, Mexico",
  "Hilton Garden Inn	Calle 17 esq. Con Jose Vasconcelos 104-108 A. Col. Vista Alegre, Merida, Yucatan. C.P. 97130 Mexico.",
  "Holiday Inn Express Siglo XXI	Av. 20 A Predio 300 Por Calle 3C Y 5A Colonia Xcumpich, Merida, Yucatan 97204",
  "Ibis Styles Galerias	Calle 3 Num 218, N 24 Y 60, Xcumpich Dentro de Plaza Galeria, 97205 Merida, Yuc.",
  "Koox Siglo XXI	Calle 50 N°493, entre calle 53 y 51, Cordemex, 97118 Merida, Yuc.",
  "Meson de la Luna	Calle 26 numero 216 x 7 y 15 Fraccionamiento Altabrisa, Merida, Yucatan, Mexico",
  "Mision Express Altabrisa	Calle 20, No. 255 entre calles 15 y 19, Fracc. Altabrisa, 97130 Merida, Yuc.",
  "Hotel Misol Ha	Calle 60 No.285 x 23 y 25, Alcala Martin, 97050 Merida, Yuc.",
  "Posada San Felipe de Jesus	Calle 7 #510,Colonia Maya, 97130 Merida, Yuc.",
  "Hotel Virreyes	Av. Cupules #60 por 6 y 6A Col. Garcia Gineres C.P. 97070 Merida Yucatan",
  "Extended Suites Merida	Calle 20-A #284 int. X 5-B y 17 colonia Revolucion, Merida, Yucatan, Mexico",
  "Zar Hotel	Av. Prolongacion paseo de Montejo no. 128 x 29 , 97125 Merida, Yucatan.",
];

const hotelesMeridaPeriferia = [
  "City Express Junior Altabrisa	Calle 4 Periferico, entre calles 7 y 9C, Santa Rita Cholul, 97130 Merida, Yuc.",
  "Hotel-Villas Dubrovnik	Km 10.3 Tablaje 21074 Carr. Merida - Progreso, Temozon Norte, Merida, Yuc.",
  "Holiday Inn Express Suites La Isla Merida	Calle 24 S/N, Temozon Norte, 97305 Merida, Yuc.",
  "Tecnohotel Norte	Carr. Merida - Progreso Km 11, Temozon Norte, Temozon Nte, 97300 Merida, Yuc.",
];

const hotelesMeridaAlrededores = [
  "Hacienda Xcanatun By Agnasa Casa de Piedra	Calle 20 S/N x 19 y 19A Comisaria Xcanatun, 97302 Merida, Yuc.",
  "Hacienda San Jose Kuche	Calle S /N Calle 13, 97345 Conkal, Yucatan,",
  "Hacienda Baspul	Chicxulub Yucatan",
  "Altozano",
  "La Ceiba",
  "Dzibilchaltun",
  "Komchen",
  "Xmatkuil",
  "Yucatan Country Club",
];

const xtravelHotelsCancun = [
  "Gota De Sal",
  "Marina El Cid/ventus",
  "Now Jade",
  "Disere Pearl",
  "Dreams Riviera",
  "Excellence Riviera",
  "H10 Coral Y Turquesa",
  "Now Sapphire",
  "Azul Beach",
  "Azul Sensatori",
  "Secrets Silversands",
  "Breathless Riviera Cancun Resort & Spa",
  "Haven Riviera Cancun",
  "Zoetry Paraiso De La Bonita",
  "Royalton Paraiso De La Bonita",
  "Moon Palace/nizuc/sunrise/grand",
  "Courtyard Marriot",
  "Nizuc",
  "Westin Resort And Spa",
  "Club Regina Cancun",
  "Sun Palace",
  "Oleo Cancun",
  "Bell Air Collection Cancun",
  "Cancun Plaza Condo",
  "Gr Caribe By Solaris",
  "Royal Solaris Cancun",
  "Solymar",
  "Now Emerald",
  "Crown Paradise",
  "Iberostar Cancun",
  "Hotel Seadust",
  "Omni",
  "Emporio",
  "Royal Caribbean",
  "Oasis Grand Cancun",
  "Oasis Cancun",
  "Fiesta Americana Condesa",
  "Marriot Casa Magna",
  "Jw Marriot",
  "Hard Rock Cancun",
  "Secrets The Vine",
  "Paradisus Cancun",
  "Sandos Cancun",
  "Golden Parnassus",
  "The Ritz Carlton",
  "Royal Sands",
  "Occidental Tucancun",
  "Live Aqua Cancun",
  "Westin Laguna Mar",
  "Park Royale Beach Cancun",
  "Me Cancun By Melia",
  "Nyx Cancun",
  "Flamingo Cancun",
  "Hyatt Zilara",
  "Panama Jack Cancun",
  "Grand Park Royal Cancun Caribe",
  "Royalton Suites Cancun",
  "Ocean Dreams Cancun",
  "Le Blanc",
  "Royal Suset",
  "Reflecct Krystal Grand Punta Cancun",
  "Krystal Cancun",
  "Aloft Cancun",
  "Clipper Club",
  "Hyatt Ziba",
  "Fiesta Americana Coral Beach",
  "Fiesta Americana Villas Cancun",
  "Riu Cancun",
  "Riu Palace Las Americas",
  "Pok Ta Pok",
  "Beachscape Kin Ha",
  "Grand Oasis Viva",
  "Dreams Sands",
  "Presidente Intercontinental",
  "Dos Playas",
  "Riu Palace Peninsula",
  "Riu Caribe",
  "Casa Maya",
  "Hilton Cancun/the Royal Cancun",
  "Oasis Palm Beach",
  "Sotavento",
  "Occidental Costa Cancun",
  "Aqua Marina",
  "Cancun Bay",
  "Ocean Spa Hotel",
  "Temptation",
  "Holiday Inn Arenas",
  "Imperial Las Perlas",
  "Ibis",
  "City Express",
  "Fiesta Inn",
  "Liverte Luxury Condos",
  "La Quinta Inn",
  "Oasis Smart",
  "Renaissance",
  "Planet Hollywood",
  "Catalonia Costa Mujeres",
  "Majestic Elegance Costa Mujeres",
  "Riu Palace Costa Mujeres",
  "Riu Dunamar",
  "Grand Palladium costa Mujeres",
  "Grand Palladium costa Mujeres Trs Coral",
  "All Ritmo Cancun",
  "Villas Del Palmar",
  "The Beloved",
  "Finest Playa Mujeres",
  "Secrets Playa Mujeres",
  "Dreams Playa Mujeres",
  "Atelier Playa Mujeres",
  "Excellence Playa Mujeres"
]

const xtravelHotelsRiviera = [
  "Mereva By Blue Sky",
  "Aluna",
  "Diameate K",
  "Poc-na",
  "Maria Del Mar",
  "Hip Hotel",
  "Mezanine",
  "Coco Limited",
  "Dune Tulum",
  "Ana & Jose Hotel Spa",
  "Punta Piedra Tulum",
  "Kore Tulum",
  "Dreams Tulum",
  "Cielo Maya",
  "Alea Tulum",
  "O'tulum",
  "Bahia Principe Sian Kaan",
  "Bahia Prinicipe Coba",
  "Bahia Principe Premier",
  "Bahia Principe Akumal",
  "Bahia Principe Tulum",
  "Sunscape Akumal",
  "Grand Sirenis",
  "Grand Palladium Riviera",
  "Grand Palladium White Sands",
  "Grand Palladium Trs",
  "Grand Palladium Colonial",
  "Grand Palladium Kantenah",
  "Unico",
  "El Dorado Sensimar Seaside Suites",
  "El Dorado Seaside Suites",
  "Catalonia Royal Tulum",
  "Bell Air Xpu-ha",
  "Barcelo Mayan Beach",
  "Barcelo Caribe",
  "Barcelo Colonial",
  "Barcelo Tropical",
  "Barcelo Mayan Palace",
  "Catalonia Riviera Maya",
  "Catalonia Yucatan Beach",
  "Dreams Puerto Aventuras",
  "Omni Puerto Aventuras",
  "Hard Rock Riviera Maya/ Heaven, Hacienda",
  "Occidental At Xcaret Destination",
  "Hotel Xcaret Mexico",
  "Riu Lupita",
  "Sandos Playacar",
  "Iberostar Tucan & Quetzal",
  "Riu Yucatan",
  "Riu Tequila",
  "Riu Palace Mexico",
  "Viva Wyndham Maya",
  "Riu Playacar",
  "Royal Hideaway",
  "Allegreo Playacar",
  "Viva Wyndham Azteca",
  "Riu Palace Riviera Maya",
  "The Reef Playacar",
  "Playacar Palace",
  "Plaza Antigua",
  "The Fives Palya Del Carmen",
  "Cocobongo",
  "Wyndham Garden",
  "Mahekal Beach",
  "Panama Jack Grand Porto Real",
  "Hilton Playa Del Carmen",
  "Real Playa Del Carmen/ Hoteles Del Centro / Reef 28",
  "Grand Hyatt Pala Del Carmen",
  "Senses Quinta Avenida",
  "Reef Coco Beach / Grand Coco bay",
  "Paradisus La Perla",
  "ParadisusEsmeralda",
  "Royal Hacienda",
  "Sandos Caracol",
  "Azul Fives By Karisma",
  "Grand Riviera Princess / Riviera, Sunset, Yucatan",
  "Ocean Riviera Paradise",
  "Grand Velas / Ambassador, Zen",
  "Rosewood Mayakoba",
  "Banyan Tree Mayakoba",
  "Fairmont Mayakoba",
  "El Dorado Royale",
  "Blue Diamond",
  "Secrets Capri",
  "Ocean Maya By H10",
  "Blue Bay Grand Esmeralda",
  "Hacienda Tres Rios",
  "El Dorado Maroma",
  "Secrets Maroma",
  "Bellmont Maroma",
  "Catalonia Maroma",
  "Iberostar Paraiso Del Mar",
  "Iberostar Paraiso Beach",
  "Iberostar Grand Paraiso",
  "Iberostar Paraiso Lindo",
  "Iberostar Paraiso Maya",
  "Senses Riviera Maya",
  "Valentin Imperial",
  "Generations Maroma"

]

export {
  hotelesCancun,
  hotelesPuertoJuarez,
  hotelesPlayaMujeres,
  hotelesPuertoMorelos,
  hotelesPlayaDelCarmen,
  hotelesPuertoAventuras,
  hotelesAkumal,
  hotelesTulum,
  hotelesMeridaAeropuerto,
  hotelesMeridaAlrededores,
  hotelesMeridaCentro,
  hotelesMeridaColonias,
  hotelesMeridaPeriferia,
  hotelesMeridaSegundoCuadro,
  xtravelHotelsCancun,
  xtravelHotelsRiviera
};
