const texts = {
  'es':
  {
    'index-v': 'Por favor, escoge un destino de la lista.',
    'index-0': 'Desde Cancún',
    'index-1': 'Desde Mérida',
    'index-2': 'Desde: ',
    'index-3': 'Tipo de experiencia: ',
    'index-4': 'Fecha',
    'index-4a': ' de ida',
    'index-5': 'Hora',
    'index-5a': 'de ida',
    'index-6': 'Hora',
    'index-7': 'Pasajeros:',
    'index-8': 'Detalles de vuelta',
    'index-9': 'Fecha de vuelta: ',
    'index-10': 'Escoge una fecha despúes de la ida.',
    'index-11': 'Hora',
    'index-12': 'Desde',
    'index-13': 'Mi Experiencia',
    'index-14': 'Favor de llenar este campo',
    'resultados-0': 'Solo ida',
    'resultados-1': 'Ida y Vuelta',
    'resultados-2': 'Regreso:',
    'resultados-3': 'Cupo Máximo: ',
    'resultados-4': 'Pasajeros',
    'resultados-5': 'Reservar',
    'resultados-6a': 'Duración máxima de',
    'resultados-6b': 'horas',
    'payscreen-0': 'Ya casi queda listo el pedido, completa los siguientes campos para brindarte el mejor servicio.',
    'payform-0': 'Revisa el campo ',
    'payform-1': '¿Cómo deseas pagar?',
    'payform-2': 'Tarjeta Bancaria',
    'payform-3': 'Pago en Oxxo',
    'payform-4': 'Datos de tarjeta',
    'payform-5': 'Titular de la tarjeta',
    'payform-6': 'Número de la tarjeta',
    'payform-7': 'Código de seguridad',
    'payform-8': 'Fecha de vencimiento',
    'payform-9': '(AAAA)',
    'payform-10': 'Nombre del títular de la reserva',
    'payform-11': 'Será la persona (Adulto) títular sel servicio.',
    'payform-12': 'Nombres y apellidos',
    'payform-13a': 'Datos del vuelo ',
    'payform-13b': 'Ida',
    'payform-14': 'Aerolínea',
    'payform-15': 'Número de vuelo',
    'payform-16': 'Hora del vuelo',
    'payform-17': 'Datos del vuelo',
    'payform-18': '/ Vuelta',
    'payform-19': 'Aerolínea',
    'payform-20': 'Número de vuelo',
    'payform-21': 'Hora del vuelo',
    'payform-22': 'Datos de contacto',
    'payform-23': 'Número de teléfono',
    'payform-24': 'Correo electrónico',
    'payform-25': 'Observaciones',
    'payform-26': 'En caso de tener requerimientos especiales por favor dejanos saber.',
    'payform-27': 'Acepto los Términos y Condiciones',
    'payform-28': 'Pagar',
    'details-0': 'Detalles de compra',
    'details-1a': 'Solo Ida',
    'details-1b': 'Ida y Vuelta',
    'details-1c': 'Excursión',
    'details-2': 'Desde: ',
    'details-3': 'Destino: ',
    'details-4': 'Fecha de excursión:',
    'details-5': 'Fecha de Vuelta: ',
    'details-6': 'Número de pasajeros:',
    'details-7a': 'pasajeros',
    'details-7b': '1 pasajero',
    'details-8': 'Precio: ',
    'upsell-0a': 'Agregar',
    'upsell-0b': 'No gracias'
  },
  'en': {
    'index-v': 'Please choose a value form the list.',
    'index-0': 'One Way',
    'index-1': 'Round Trip ',
    'index-2': 'From: ',
    'index-3': 'Type of Experience: ',
    'index-4': 'Date',
    'index-4a': ' leaving',
    'index-5': 'Time',
    'index-5a': 'leaving',
    'index-6': 'Time',
    'index-7': 'Passengers:',
    'index-8': 'Return Details',
    'index-9': 'Return Date: ',
    'index-10': 'Choose a date after your departure.',
    'index-11': 'Time',
    'index-12': 'From',
    'index-13': 'My Experience',
    'index-14': 'Please fill out this field',
    'resultados-0': 'One Way',
    'resultados-1': 'Round Trip',
    'resultados-2': 'Return:',
    'resultados-3': 'Maximum passengers: ',
    'resultados-4': 'Passengers',
    'resultados-5': 'Reserve',
    'resultados-6a': 'Maximum duration of',
    'resultados-6b': 'hours',
    'payscreen-0': 'Your reservation is almost ready. Complete the following fields in order to provide you with a better experience.',
    'payform-0': 'Check the field ',
    'payform-1': 'How will you pay?',
    'payform-2': 'Credit or Debit',
    'payform-3': 'Pay in Oxxo',
    'payform-4': 'Card details',
    'payform-5': 'Cardholder Name',
    'payform-6': 'Card Number',
    'payform-7': 'Security Code',
    'payform-8': 'Expiration Date',
    'payform-9': '(YYYY)',
    'payform-10': "Reservation holder's name",
    'payform-11': 'This is the person (adult) whose name the service will be in.',
    'payform-12': 'Full Name',
    'payform-13a': 'Flight details ',
    'payform-13b': '/ Departure',
    'payform-14': 'Airline',
    'payform-15': 'Flight number',
    'payform-16': 'Flight time',
    'payform-17': 'Flight details',
    'payform-18': '/ Return',
    'payform-19': 'Airline',
    'payform-20': 'Flight number',
    'payform-21': 'Flight time',
    'payform-22': 'Contact Details',
    'payform-23': 'Phone number',
    'payform-24': 'Email address',
    'payform-25': 'Notes',
    'payform-26': 'If you have special requirements, please let us know.',
    'payform-27': 'I accept the Terms and Conditions',
    'payform-28': 'Pay',
    'details-0': 'Purchase Details',
    'details-1a': 'One Way',
    'details-1b': 'Round Trip',
    'details-1c': 'Excursion',
    'details-2': 'From: ',
    'details-3': 'To: ',
    'details-4': 'Excursion Date:',
    'details-5': 'Return Date: ',
    'details-6': 'Number of passengers:',
    'details-7a': 'passengers',
    'details-7b': '1 passenger',
    'details-8': 'Price: ',
    'upsell-0a': 'Add',
    'upsell-0b': 'No thanks'

  }
}

export default texts;